name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: netcdf
      run: sudo apt-get install libnetcdf-dev
    - name: make
      run: make fpocket
    - name: create conda environment
      run: conda env update -f ./tests/environment.yml     
    - name: activate conda environment
      run : source /usr/share/miniconda/etc/profile.d/conda.sh
            activate fpocket_test      
            pytest1
