name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: netcdf
      run: sudo apt-get install libnetcdf-dev
    - name: make
      run: make fpocket
    - name: create conda environment
      uses: fpocket/conda-action@v2
      with: 
        args: conda env update -f ./tests/environment.yml     
    - name: run pytest
      uses: fpocket/conda-action@v2
      with: 
        args: pytest
