name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: netcdf
      run: apt-get install libnetcdf-dev
    - name: make
      run: make fpocket
    
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make fpocket -ARCH=MACOSXX86_64
